### ISSUE TITLE
 Navigating next in module stack from Relax closes stack

### ISSUE THREAD

**Issue by esmeetewinkel** [ParentingForLifelongHealth/plh-kids-app-kw-content#88]
First observed in #87

**Comment by esmeetewinkel** [comment]
@jfmcquade thanks for looking into this! 

I agree I've found this happens mostly around Check-in and Relax articles - which are a bit different from other articles: they come from separate data lists (of "all checkins" and "all relaxes") and are appended onto the list of articles for one module afterwards. 

Will let you know if I find out any more details / hypothesis / fix

**Comment by jfmcquade** [comment]
This should be resolved by [#2605](https://github.com/IDEMSInternational/open-app-builder/pull/2605) (now merged), but I'm adding documentation of the bug here for reference:

[debug_modal_interactions](https://docs.google.com/spreadsheets/d/1IUHvMxxNLfwVTPdtNO-yKuhj8QJ9K-qr24WP9LMwBLc/edit?gid=1422144003#gid=1422144003). 

<img width="800" alt="Screenshot 2024-12-07 at 15 01 02" src="https://github.com/user-attachments/assets/6441dc15-c95a-4a16-9b16-6f910916710f">

https://github.com/user-attachments/assets/b11d07e9-d1e3-4727-a57c-a50c312a8ca7
